### ISSUE TITLE
peletakan vendor sejajar application.

### ISSUE THREAD

**Issue by titounnes** [Ardhie1032/CodeIgniter3-starter#1]
Bagaimana kalo third_party diletakkan sejajar dengan application? 
biar librarynya bisa digunakan beberapa application sekaligus dengan lebih mudah.

**Comment by Ardhie1032** [comment]
Kalo third party di luar folder application, saya gak tahu cara merelokasinya :D Rencana mau dibikin juga buat composer. Cuma masalahnya, library autoloder class nya jadi gak berguna.

**Comment by Ardhie1032** [comment]
Update... silahken dicoba.
